/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceinvander;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GraphicsConfiguration;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;

/**
 *
 * @author Godievski
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    private final Nave nave;
    private int keyPressed;
    private boolean disparando;
    private final ProcesoEnemigo enemigos;
    private final ControlarColisiones controladorColisiones;
    protected static int score;
    private final static int SLEEP_TIME = 10;
    protected final static int WINDOW_WIDTH = 400;
    protected final static int WINDOW_HEIGHT = 600;
    
    
    /*TEST*/
    private Image dibujoAux;
    private Graphics gAux;
    private Dimension dimAux;
    private final Dimension dimPanel;
    /**/
    
    /**
     *
     * @param graphicConf
     */
    public Game(GraphicsConfiguration graphicConf) {
        super(graphicConf);
        //this.setIgnoreRepaint(true);
        initComponents();
        this.setBounds(500, 100, Game.WINDOW_WIDTH+6, Game.WINDOW_HEIGHT+28);
        this.jPanel1.setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        this.setResizable(false);
        this.createBufferStrategy(3);
        this.setVisible(true);
        jPanel1.setDoubleBuffered(true);
        this.setTitle("SpaceInvader by Godievski");
        dimPanel = jPanel1.getSize();
        //OBJETOS DEL JUEGO
        nave = new Nave();
        this.enemigos = new ProcesoEnemigo();
        this.controladorColisiones = new ControlarColisiones(this.nave,this.enemigos);
        this.keyPressed = 0;
        Game.score = 0;
    }

    public void play(){
        this.enemigos.start();
        this.controladorColisiones.start();
        while (true){
            try {
                nave.mover(this.keyPressed);
                repaint();
                sleep(SLEEP_TIME);
            } catch (InterruptedException ex) {
                Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void dibujarEnemigos(Graphics g){

        if (enemigos == null || enemigos.listaEnemy == null)
            return;
        try {
            g.setColor(Color.BLACK);
            for (int i = 0; i < enemigos.listaEnemy.size(); i++){
                Enemy enemy = enemigos.listaEnemy.get(i);
                g.fillOval(enemy.posX, enemy.posY, enemy.width, enemy.height);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    
    @Override
    public void update(Graphics graph){
        paint(graph);
    }
    
    @Override
    public void paint (Graphics graph){
        
        this.jPanel1.paint(graph);
        if (gAux == null || dimAux == null || dimPanel.width != dimAux.width ||
                dimPanel.height != dimAux.height){
            dimAux = dimPanel;
            dibujoAux = createImage(dimAux.width,dimAux.height);
            gAux = dibujoAux.getGraphics();
        }

        Graphics g = jPanel1.getGraphics();
        
        //FONDO
        gAux.setColor(Color.MAGENTA);
        gAux.fillRect(0, 0, Game.WINDOW_WIDTH, Game.WINDOW_HEIGHT);
        
        //DIBUJAR PUNTAJE
        gAux.setColor(Color.WHITE);
        gAux.drawString("Score: " + Game.score, 10, 20);
        
        //DIBUJAR NAVE Y ENEMIGOS
        if (nave != null)
            nave.dibujar(gAux);

        //DIBUJAR ENEMIGOS
        dibujarEnemigos(gAux);
        
        g.drawImage(dibujoAux, 0, 0, jPanel1);
        
        g.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        
        if (code == KeyEvent.VK_LEFT || code == KeyEvent.VK_RIGHT)
            this.keyPressed = code;
        
            
        if (code == KeyEvent.VK_SPACE)
            nave.disparar();            
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
